# Generated by Django 3.2 on 2021-05-28 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0003_auto_20210523_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.DeleteModel(
            name='PostComment',
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
